default_config:
logger:
  default: error
  logs:
    custom_components.jellyfin_upcoming_media: debug

sensor:
  - platform: jellyfin_upcoming_media
    api_key: !secret jellyfin_api_key
    user_id: !secret jellyfin_user_id
    port: 443
    host: !secret jellyfin_host
    ssl: True
    max: 5
    include:
      - Movies
      - TV Shows
      - Kids Movies [EN]
      - Kids Movies [FR]